baseURL = "https://matneves.github.io/beiramar-site/"
languageCode = "pt-br"
theme = "beiramar"
publishDir = "docs"
DefaultContentLanguage = "pt"

[Languages]

[Languages.pt]
title = "Beira Mar Serviços Marítimos LTDA"
[Languages.en]
title = "Beira Mar Serviços Marítimos LTDA"